"""
optimizer.py — SmartDTC Cyclic Bus Schedule Optimizer v2.0

Key insight: buses are NOT used once. Each bus cycles:
  departure -> trip (trip_duration_min) -> turnaround (turnaround_min) -> next departure

With F buses and cycle_time = trip_duration_min + turnaround_min:
  * minimum achievable headway = cycle_time / F
  * trips per bus per day      = floor(window_min / cycle_time)
  * total trips per day        = F x trips_per_bus

The GA optimises F initial phase-offsets within one cycle window [0, cycle_time).
All subsequent trips are auto-generated by repeating every cycle_time minutes.

Example: 5 buses, 90 min trip, 15 min turnaround:
  cycle = 105 min, min headway = 21 min
  In an 18-hour day each bus does ~10 trips -> 50 total trips.
"""

import logging
import math
from typing import List, Dict, Tuple

try:
    import predictors as _pred
except Exception:
    _pred = None

logger = logging.getLogger(__name__)

HOUR_BASE_DEMAND = {
    0: 10,  1: 8,   2: 6,   3: 5,   4: 8,   5: 20,
    6: 40,  7: 80,  8: 120, 9: 100, 10: 60, 11: 50,
    12: 70, 13: 65, 14: 55, 15: 60, 16: 75, 17: 110,
    18: 130, 19: 100, 20: 70, 21: 50, 22: 35, 23: 20,
}


def _demand_at_hour(hour: int, is_weekend: bool = False, is_holiday: bool = False) -> float:
    base = HOUR_BASE_DEMAND.get(hour, 30)
    if is_holiday:
        factor = 0.6 if hour in range(7, 10) else 1.1 if hour in range(11, 16) else 0.8
    elif is_weekend:
        factor = 0.5 if hour in range(7, 10) else 1.0 if hour in range(11, 20) else 0.7
    else:
        factor = 1.0
    return max(5.0, base * factor)


def _total_wait_time(departures: List[int], demand_curve: List[float],
                     start_min: int, end_min: int) -> float:
    if not departures:
        return 1e9
    times = [start_min] + sorted(departures) + [end_min]
    total = 0.0
    for i in range(len(times) - 1):
        gap    = times[i + 1] - times[i]
        hour   = min(times[i] // 60, 23)
        demand = demand_curve[hour]
        total += demand * (gap / 2.0)
    return total


def optimize_headway(
    route_id:          str,
    date:              str,
    fleet_size:        int,
    trip_duration_min: int  = 90,
    turnaround_min:    int  = 15,
    is_weekend:        bool = False,
    is_holiday:        bool = False,
    start_hour:        int  = 5,
    end_hour:          int  = 23,
) -> Dict:
    """
    Cyclic GA for bus scheduling.
    Each bus b departs at: start_min + offset_b, then every cycle_time minutes.
    GA evolves the F-element offset vector to minimise total passenger wait time.
    """
    cycle_time = trip_duration_min + turnaround_min
    start_min  = start_hour * 60
    end_min    = end_hour   * 60
    window     = end_min - start_min

    if cycle_time <= 0 or window <= 0:
        return {"error": "Invalid cycle_time or window", "slots": []}

    min_headway    = math.ceil(cycle_time / fleet_size)
    max_per_bus    = max(1, window // cycle_time)
    expected_trips = fleet_size * max_per_bus

    # ── Bus count recommendations for common target headways ─────────────────
    recommendations = {}
    for target_min in [3, 5, 8, 10, 15, 20, 30]:
        recommendations[f"{target_min}min"] = math.ceil(cycle_time / target_min)

    demand_curve = [_demand_at_hour(h, is_weekend, is_holiday) for h in range(24)]

    # ── Peak demand and demand-optimal headway ───────────────────────────────
    peak_demand   = max(demand_curve)
    avg_demand    = sum(demand_curve) / 24
    # BRT capacity: ~80 seated + standing. Optimal headway to keep load ≤ 85%.
    capacity      = 80
    # At peak demand D (pax/hr), headway H (min): passengers per trip = D * H/60
    # Keep ≤ capacity*0.85 → H ≤ capacity*0.85*60/D
    demand_optimal_headway = max(3, int(capacity * 0.85 * 60 / peak_demand))
    demand_optimal_buses   = math.ceil(cycle_time / demand_optimal_headway)

    def expand(offsets: List[int]) -> List[Tuple[int, int, int]]:
        """Generate all (departure_min, bus_idx, trip_num) tuples for the day."""
        trips = []
        for bus_idx, offset in enumerate(offsets):   # preserve bus identity order
            dep      = start_min + (offset % cycle_time)
            trip_num = 0
            while dep < end_min:
                trips.append((dep, bus_idx, trip_num))
                dep      += cycle_time
                trip_num += 1
        return sorted(trips, key=lambda x: x[0])

    def departures_of(offsets: List[int]) -> List[int]:
        return [t[0] for t in expand(offsets)]

    # ── Demand-aware phase optimisation ──────────────────────────────────────
    # Buses are ALWAYS evenly spaced by cycle_time / fleet_size minutes.
    # The AI searches for the single best base_phase (0..cycle_time-1 min)
    # that shifts the whole evenly-spaced fleet to minimise total
    # passenger-weighted wait time (aligns peak service with peak demand).
    even_gap = cycle_time / fleet_size   # exact float gap between buses

    def make_offsets(base_phase: int) -> List[int]:
        """Return fleet_size evenly-spaced offsets starting at base_phase."""
        return [int((base_phase + i * even_gap) % cycle_time) for i in range(fleet_size)]

    def score_phase(base_phase: int) -> float:
        return _total_wait_time(departures_of(make_offsets(base_phase)),
                                demand_curve, start_min, end_min)

    # Full scan over every minute — fast (cycle_time ≤ 420 min)
    best_phase      = min(range(cycle_time), key=score_phase)
    best_score      = score_phase(best_phase)
    best            = make_offsets(best_phase)
    convergence_gen = best_phase   # repurposed as "optimal base phase (min)"

    logger.info(
        f"Phase scan: route={route_id}, {fleet_size} buses, "
        f"cycle={cycle_time}min, headway={min_headway}min, "
        f"best_phase={best_phase}min, ~{expected_trips} total trips ({start_hour}h-{end_hour}h)"
    )

    def min_to_time(m: int) -> str:
        h, mn = divmod(int(m) % (24 * 60), 60)
        return f"{h:02d}:{mn:02d}"

    final_trips   = expand(best)
    trips_per_bus = [0] * fleet_size
    slots         = []
    prev_dep      = None

    for (dep, bus_idx, trip_num) in final_trips:
        headway = dep - prev_dep if prev_dep is not None else 0
        hour    = min(dep // 60, 23)
        arrival = dep + trip_duration_min

        ml_demand: float = demand_curve[hour]
        if _pred is not None:
            try:
                ml_result = _pred.predict_demand(
                    route_id=route_id, date=date, hour=hour,
                    is_weekend=is_weekend, is_holiday=is_holiday,
                    weather="clear", avg_temp_c=30.0,
                    special_event=False, model_key="auto",
                )
                ml_demand = float(ml_result.get("predicted_count", ml_demand))
            except Exception:
                pass

        crowd = (
            "very_high" if ml_demand > 160 else
            "high"      if ml_demand > 100 else
            "medium"    if ml_demand > 60  else "low"
        )

        slots.append({
            "departure_min":      dep,
            "departure_time_str": min_to_time(dep),
            "arrival_time_str":   min_to_time(arrival),
            "duration_min":       trip_duration_min,
            "hour":               hour,
            "headway_min":        headway,
            "bus_number":         bus_idx + 1,
            "trip_number":        trip_num + 1,
            "demand_score":       round(ml_demand, 1),
            "crowd_level":        crowd,
        })
        trips_per_bus[bus_idx] += 1
        prev_dep = dep

    logger.info(
        f"GA done: converged gen={convergence_gen}, score={best_score:.1f}, "
        f"total_trips={len(slots)}, trips_per_bus={trips_per_bus}"
    )

    return {
        "route_id":                  route_id,
        "date":                      date,
        "fleet_size":                fleet_size,
        "trip_duration_min":         trip_duration_min,
        "turnaround_min":            turnaround_min,
        "cycle_time_min":            cycle_time,
        "min_headway_min":           min_headway,
        "total_trips":               len(slots),
        "trips_per_bus":             trips_per_bus,
        "slots":                     slots,
        "total_wait_score":          round(best_score, 2),
        "recommendations": {
            "buses_for_headway":         recommendations,
            "demand_optimal_headway_min": demand_optimal_headway,
            "demand_optimal_buses":       demand_optimal_buses,
            "peak_demand_per_hour":       round(peak_demand, 1),
            "avg_demand_per_hour":        round(avg_demand, 1),
            "note": (
                f"Peak demand {round(peak_demand,0):.0f} pax/h. "
                f"To keep buses ≤85% full, use headway ≤{demand_optimal_headway} min "
                f"({demand_optimal_buses} buses needed)."
            ),
        },
        "optimization_info": {
            "algorithm":           "Even-spacing + demand-aware phase scan",
            "optimal_base_phase":  best_phase,
            "wait_score":          round(best_score, 2),
            "even_gap_min":        round(even_gap, 2),
            "note": (
                f"{fleet_size} buses evenly spaced every {round(even_gap,1)} min. "
                f"Fleet start at offset {best_phase} min minimises passenger wait. "
                f"Min headway = {min_headway} min. ~{expected_trips} total trips."
            ),
        },
    }
