"""
optimizer.py — SmartDTC Cyclic Bus Schedule Optimizer v2.0

Key insight: buses are NOT used once. Each bus cycles:
  departure -> trip (trip_duration_min) -> turnaround (turnaround_min) -> next departure

With F buses and cycle_time = trip_duration_min + turnaround_min:
  * minimum achievable headway = cycle_time / F
  * trips per bus per day      = floor(window_min / cycle_time)
  * total trips per day        = F x trips_per_bus

The GA optimises F initial phase-offsets within one cycle window [0, cycle_time).
All subsequent trips are auto-generated by repeating every cycle_time minutes.

Example: 5 buses, 90 min trip, 15 min turnaround:
  cycle = 105 min, min headway = 21 min
  In an 18-hour day each bus does ~10 trips -> 50 total trips.
"""

import logging
import random
import math
from typing import List, Dict, Tuple

try:
    import predictors as _pred
except Exception:
    _pred = None

logger = logging.getLogger(__name__)

HOUR_BASE_DEMAND = {
    0: 10,  1: 8,   2: 6,   3: 5,   4: 8,   5: 20,
    6: 40,  7: 80,  8: 120, 9: 100, 10: 60, 11: 50,
    12: 70, 13: 65, 14: 55, 15: 60, 16: 75, 17: 110,
    18: 130, 19: 100, 20: 70, 21: 50, 22: 35, 23: 20,
}


def _demand_at_hour(hour: int, is_weekend: bool = False, is_holiday: bool = False) -> float:
    base = HOUR_BASE_DEMAND.get(hour, 30)
    if is_holiday:
        factor = 0.6 if hour in range(7, 10) else 1.1 if hour in range(11, 16) else 0.8
    elif is_weekend:
        factor = 0.5 if hour in range(7, 10) else 1.0 if hour in range(11, 20) else 0.7
    else:
        factor = 1.0
    return max(5.0, base * factor)


def _total_wait_time(departures: List[int], demand_curve: List[float],
                     start_min: int, end_min: int) -> float:
    if not departures:
        return 1e9
    times = [start_min] + sorted(departures) + [end_min]
    total = 0.0
    for i in range(len(times) - 1):
        gap    = times[i + 1] - times[i]
        hour   = min(times[i] // 60, 23)
        demand = demand_curve[hour]
        total += demand * (gap / 2.0)
    return total


def optimize_headway(
    route_id:          str,
    date:              str,
    fleet_size:        int,
    trip_duration_min: int  = 90,
    turnaround_min:    int  = 15,
    is_weekend:        bool = False,
    is_holiday:        bool = False,
    start_hour:        int  = 5,
    end_hour:          int  = 23,
    population_size:   int  = 60,
    generations:       int  = 120,
) -> Dict:
    """
    Cyclic GA for bus scheduling.
    Each bus b departs at: start_min + offset_b, then every cycle_time minutes.
    GA evolves the F-element offset vector to minimise total passenger wait time.
    """
    cycle_time = trip_duration_min + turnaround_min
    start_min  = start_hour * 60
    end_min    = end_hour   * 60
    window     = end_min - start_min

    if cycle_time <= 0 or window <= 0:
        return {"error": "Invalid cycle_time or window", "slots": []}

    min_headway    = math.ceil(cycle_time / fleet_size)
    max_per_bus    = max(1, window // cycle_time)
    expected_trips = fleet_size * max_per_bus

    demand_curve = [_demand_at_hour(h, is_weekend, is_holiday) for h in range(24)]

    logger.info(
        f"Cyclic GA: route={route_id}, {fleet_size} buses, "
        f"cycle={cycle_time}min, min_headway={min_headway}min, "
        f"~{expected_trips} total trips over {start_hour}h-{end_hour}h"
    )

    def expand(offsets: List[int]) -> List[Tuple[int, int, int]]:
        trips = []
        for bus_idx, offset in enumerate(sorted(offsets)):
            dep      = start_min + (offset % cycle_time)
            trip_num = 0
            while dep < end_min:
                trips.append((dep, bus_idx, trip_num))
                dep      += cycle_time
                trip_num += 1
        return sorted(trips, key=lambda x: x[0])

    def departures_of(offsets: List[int]) -> List[int]:
        return [t[0] for t in expand(offsets)]

    def random_individual() -> List[int]:
        n = min(fleet_size, cycle_time)
        return sorted(random.sample(range(0, cycle_time), n))

    def crossover(p1: List[int], p2: List[int]) -> List[int]:
        if len(p1) < 2:
            return p1[:]
        point = random.randint(1, len(p1) - 1)
        child = sorted(set(p1[:point] + p2[point:]))
        while len(child) < fleet_size:
            t = random.randint(0, cycle_time - 1)
            if t not in child:
                child.append(t)
                child.sort()
        return child[:fleet_size]

    def mutate(individual: List[int], rate: float = 0.25) -> List[int]:
        mutated     = individual[:]
        used        = set(mutated)
        shift_range = max(5, cycle_time // 6)
        for i in range(len(mutated)):
            if random.random() < rate:
                new_t = (mutated[i] + random.randint(-shift_range, shift_range)) % cycle_time
                if new_t not in used:
                    used.discard(mutated[i])
                    mutated[i] = new_t
                    used.add(new_t)
        return sorted(mutated)

    def score(offsets: List[int]) -> float:
        return _total_wait_time(departures_of(offsets), demand_curve, start_min, end_min)

    population      = [random_individual() for _ in range(population_size)]
    best            = min(population, key=score)
    best_score      = score(best)
    convergence_gen = 0

    for gen in range(generations):
        scored = sorted([(score(ind), ind) for ind in population], key=lambda x: x[0])

        elite_n = max(2, population_size // 10)
        new_pop = [ind for _, ind in scored[:elite_n]]

        while len(new_pop) < population_size:
            t1    = min(random.sample(scored, min(4, len(scored))), key=lambda x: x[0])[1]
            t2    = min(random.sample(scored, min(4, len(scored))), key=lambda x: x[0])[1]
            child = mutate(crossover(t1, t2))
            if len(child) == fleet_size:
                new_pop.append(child)

        population = new_pop
        gen_best   = scored[0][0]
        if gen_best < best_score:
            best_score      = gen_best
            best            = scored[0][1]
            convergence_gen = gen

    def min_to_time(m: int) -> str:
        h, mn = divmod(int(m) % (24 * 60), 60)
        return f"{h:02d}:{mn:02d}"

    final_trips   = expand(best)
    trips_per_bus = [0] * fleet_size
    slots         = []
    prev_dep      = None

    for (dep, bus_idx, trip_num) in final_trips:
        headway = dep - prev_dep if prev_dep is not None else 0
        hour    = min(dep // 60, 23)
        arrival = dep + trip_duration_min

        ml_demand: float = demand_curve[hour]
        if _pred is not None:
            try:
                ml_result = _pred.predict_demand(
                    route_id=route_id, date=date, hour=hour,
                    is_weekend=is_weekend, is_holiday=is_holiday,
                    weather="clear", avg_temp_c=30.0,
                    special_event=False, model_key="auto",
                )
                ml_demand = float(ml_result.get("predicted_count", ml_demand))
            except Exception:
                pass

        crowd = (
            "very_high" if ml_demand > 160 else
            "high"      if ml_demand > 100 else
            "medium"    if ml_demand > 60  else "low"
        )

        slots.append({
            "departure_min":      dep,
            "departure_time_str": min_to_time(dep),
            "arrival_time_str":   min_to_time(arrival),
            "duration_min":       trip_duration_min,
            "hour":               hour,
            "headway_min":        headway,
            "bus_number":         bus_idx + 1,
            "trip_number":        trip_num + 1,
            "demand_score":       round(ml_demand, 1),
            "crowd_level":        crowd,
        })
        trips_per_bus[bus_idx] += 1
        prev_dep = dep

    logger.info(
        f"GA done: converged gen={convergence_gen}, score={best_score:.1f}, "
        f"total_trips={len(slots)}, trips_per_bus={trips_per_bus}"
    )

    return {
        "route_id":          route_id,
        "date":              date,
        "fleet_size":        fleet_size,
        "trip_duration_min": trip_duration_min,
        "turnaround_min":    turnaround_min,
        "cycle_time_min":    cycle_time,
        "min_headway_min":   min_headway,
        "total_trips":       len(slots),
        "trips_per_bus":     trips_per_bus,
        "slots":             slots,
        "total_wait_score":  round(best_score, 2),
        "optimization_info": {
            "generations":      generations,
            "population_size":  population_size,
            "convergence_gen":  convergence_gen,
            "algorithm":        "Cyclic GA - phase-offset optimisation per bus",
            "note": (
                f"{fleet_size} buses x ~{max_per_bus} trips/bus = ~{expected_trips} total trips. "
                f"Min headway = {min_headway} min (cycle {cycle_time} min / {fleet_size} buses)."
            ),
        },
    }
